### ISSUE TITLE
Can't update the package because of wrong reference to errs package

### ISSUE THREAD

**Issue by galeone** [goark/pa-api#23]
Hi! I was looking for some update in a project, and when I typed

```
go get -u github.com/spiegel-im-spiegel/pa-api
```

here's what I got:
```
go get: github.com/spiegel-im-spiegel/errs@v1.1.0: parsing go.mod:
        module declares its path as: github.com/goark/errs
                but was required as: github.com/spiegel-im-spiegel/errs
```

I guess [this line](https://github.com/spiegel-im-spiegel/pa-api/blob/master/go.mod#L6) should be updated according to the new `errs` package location :smile:

**Comment by spiegel-im-spiegel** [comment]
I am migrating my Go packages to @goark organization repositories. 
I will respond within 24 hours, so please wait a little longer.

**Comment by spiegel-im-spiegel** [comment]
Migrated repository to github.com/goark/pa-api

```
$ go get -u github.com/goark/pa-api@latest
go: downloading github.com/goark/pa-api v0.11.0
go: downloading github.com/goark/errs v1.1.0
go: downloading github.com/goark/fetch v0.3.0
```
