### ISSUE TITLE
Enable to get browse node Info

### ISSUE THREAD

**Issue by isaka1022** [goark/pa-api#25]
Hello everyone,

I want to get BrowseNode information through GetBrowseNodes  operation on paapi5.
https://webservices.amazon.com/paapi5/documentation/getbrowsenodes.html

## Usecase

I would like to get BrowseNode information as SearchItems and GetItems operations in pa-api library like below.

```
//Make query
    q := query.GetBrowseNodes(
        client.Marketplace(),
        client.PartnerTag(),
        client.PartnerType(),
    ). BrowseNodeIds([]string{"3040", "3045"})
```

**Comment by spiegel-im-spiegel** [comment]
Code below:

```go
//Make query
q := query.NewBrowseNodes(
    client.Marketplace(),
    client.PartnerTag(),
    client.PartnerType(),
).BrowseNodeIds([]string{"3040", "3045"}).EnableBrowseNodes()
```

**Comment by isaka1022** [comment]
Thank you for your prompt response!
I have created an additional PR related to this. 
https://github.com/goark/pa-api/pull/27

**Comment by spiegel-im-spiegel** [comment]
Many thanks!
