### ISSUE TITLE
`ParentASIN` attribute not present in `Item` struct

### ISSUE THREAD

**Issue by giwiro** [goark/pa-api#29]
First of all great work with the go PAapi, it was really helpful.

The issue here is that the response mapping process is missing an attribute `ParentASIN` in the `Item` struct.
If the selected ASIN is a variant option (e.x. https://www.amazon.com/dp/B08GQHCJVZ) and it has the `EnabEnableParentASIN` the `Response > Item` struct does not seem to have that property.

**Comment by giwiro** [comment]
Hopefully this PR will do it: https://github.com/goark/pa-api/pull/30

**Comment by spiegel-im-spiegel** [comment]
Thanks for your pull request. Released [v0.12.2](https://github.com/goark/pa-api/releases/tag/v0.12.2)
